

file:
  path: /home/floy/imgs/



spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/potion_db
    username: potion_user
    password: 2F$[NQ,ZJFpY8Pavl8pFEEL2SaYYFLK
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

server:
  port: 8080
